#!/bin/sh

make -C /home/migs/android/shooter-u-gb-crc-2.6.35-215f227 M=/home/migs/android/wpthis/gfmod
make -C /home/migs/android/shooter-u-gb-crc-2.6.35-215f227 M=/home/migs/android/wpthis/gkmem
./embedwpthis.pl
make clean
make all